### PR TITLE
Address review comments

### PR DESCRIPTION
**Pull request by barbogast**

### CODE REVIEW

**Comment by barbogast** [comment]
Best reviewed by commit.

**Comment by barbogast** [comment]
Oups, just saw your existing commit... I guess you can still pull some of the commits in here, if you think it helps...

**Comment by barbogast** [comment]
https://github.com/TheEhsanSarshar/zustand/pull/3/commits/cddce7ba0322b9b15ff1439e3588d82186d40c6a might still be worth merging, it IMO simplifies the code quite nicely.

**Comment by TheEhsanSarshar** [comment]
Thank you @barbogast.
I think if you uncommit cddce7ba0322b9b15ff1439e3588d82186d40c6a and 11221beeb765001a1d5bd140ace23d88924aaa70.
it is easier to track the new changes.

**Comment by byteab** [comment]
as it seems the two top commits have many moving part. can you please drop them.

**Pull request closed without merging**
